version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/dpetzold/terraform-aws-serverless
    steps:
      - checkout
      - run: go test -v ./...
